//! Reproducible task understanding.
//!
//! Before any patch is generated, ContribAI builds a structured
//! [`TaskSpec`] from authorized inputs: issue text, maintainer comments,
//! repository contribution instructions, repository policy, and local code
//! context. Requirements are provenance-tagged so a maintainer can always
//! tell explicit instructions apart from model hypotheses.
//!
//! A deterministic fingerprint covers the normalized specification, and a
//! separate source digest detects stale maintainer input before submission.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Where a requirement came from. Inferred requirements must never be
/// presented as explicit maintainer instructions.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RequirementProvenance {
    /// Written by a maintainer (issue body, maintainer comment, label intent).
    MaintainerAuthored,
    /// Read from the repository (contribution guide, policy, existing code).
    RepositoryFact,
    /// Generated by the model from context; not an instruction.
    ModelHypothesis,
    /// Model-derived acceptance criterion; bounded and checkable.
    InferredCriterion,
}

impl RequirementProvenance {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::MaintainerAuthored => "maintainer_authored",
            Self::RepositoryFact => "repository_fact",
            Self::ModelHypothesis => "model_hypothesis",
            Self::InferredCriterion => "inferred_criterion",
        }
    }
}

/// One requirement or fact feeding the task, tagged by origin.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskRequirement {
    pub text: String,
    pub provenance: RequirementProvenance,
}

/// A bounded, checkable acceptance condition.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AcceptanceCriterion {
    pub description: String,
    pub provenance: RequirementProvenance,
    /// How the criterion can be checked: `command`, `path_change`, `manual`.
    pub check_kind: String,
}

/// Structured understanding of one authorized task.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskSpec {
    pub repository: String,
    pub issue: Option<i64>,
    pub title: String,
    pub requirements: Vec<TaskRequirement>,
    pub acceptance_criteria: Vec<AcceptanceCriterion>,
    /// Explicitly unresolved questions surfaced to the reviewer.
    pub ambiguities: Vec<String>,
    /// Fingerprint over the normalized spec (set by [`TaskSpec::finalize`]).
    pub fingerprint: String,
    /// Digest of the normalized authorized inputs, for staleness detection.
    pub source_digest: String,
    pub created_at: DateTime<Utc>,
}

/// Normalized maintainer-authored inputs whose change invalidates a spec.
#[derive(Debug, Clone, Default)]
pub struct TaskInputs<'a> {
    pub issue_title: &'a str,
    pub issue_body: &'a str,
    /// Maintainer comments only — untrusted third-party comments do not
    /// belong in the staleness digest.
    pub maintainer_comments: &'a [String],
    /// Relevant excerpt of repository contribution policy.
    pub policy_excerpt: &'a str,
}

impl TaskSpec {
    /// Build an unfinalized spec. Fingerprints are assigned by [`finalize`].
    pub fn draft(
        repository: impl Into<String>,
        issue: Option<i64>,
        title: impl Into<String>,
    ) -> Self {
        Self {
            repository: repository.into(),
            issue,
            title: title.into(),
            requirements: Vec::new(),
            acceptance_criteria: Vec::new(),
            ambiguities: Vec::new(),
            fingerprint: String::new(),
            source_digest: String::new(),
            created_at: Utc::now(),
        }
    }

    /// Digest of the normalized authorized inputs. If issue text, maintainer
    /// comments, or policy materially change before submission, this digest
    /// changes and the run must not silently continue.
    pub fn compute_source_digest(inputs: &TaskInputs<'_>) -> String {
        let mut digest = Sha256::new();
        digest.update(b"contribai-task-inputs-v1");
        for field in [
            normalize_ws(inputs.issue_title),
            normalize_ws(inputs.issue_body),
            normalize_ws(inputs.policy_excerpt),
        ] {
            hash_len_prefixed(&mut digest, field.as_bytes());
        }
        hash_len_prefixed(
            &mut digest,
            &(inputs.maintainer_comments.len() as u64).to_be_bytes(),
        );
        for comment in inputs.maintainer_comments {
            hash_len_prefixed(&mut digest, normalize_ws(comment).as_bytes());
        }
        hex::encode(digest.finalize())
    }

    /// Seal the spec: assign the source digest and the spec fingerprint.
    pub fn finalize(mut self, inputs: &TaskInputs<'_>) -> Self {
        self.source_digest = Self::compute_source_digest(inputs);
        self.fingerprint = self.compute_fingerprint();
        self
    }

    /// Recompute the deterministic fingerprint over normalized content.
    pub fn compute_fingerprint(&self) -> String {
        let mut digest = Sha256::new();
        digest.update(b"contribai-task-spec-v1");
        for field in [
            self.repository.clone(),
            self.issue.map(|n| n.to_string()).unwrap_or_default(),
            normalize_ws(&self.title),
            self.source_digest.clone(),
        ] {
            hash_len_prefixed(&mut digest, field.as_bytes());
        }
        for req in &self.requirements {
            hash_len_prefixed(&mut digest, req.provenance.as_str().as_bytes());
            hash_len_prefixed(&mut digest, normalize_ws(&req.text).as_bytes());
        }
        for criterion in &self.acceptance_criteria {
            hash_len_prefixed(&mut digest, criterion.provenance.as_str().as_bytes());
            hash_len_prefixed(&mut digest, normalize_ws(&criterion.description).as_bytes());
            hash_len_prefixed(&mut digest, criterion.check_kind.as_bytes());
        }
        for ambiguity in &self.ambiguities {
            hash_len_prefixed(&mut digest, normalize_ws(ambiguity).as_bytes());
        }
        hex::encode(digest.finalize())
    }

    /// Whether maintainer-authored inputs still match the sealed digest.
    pub fn inputs_are_current(&self, inputs: &TaskInputs<'_>) -> bool {
        self.source_digest == Self::compute_source_digest(inputs)
    }

    /// Count of requirements asserted by a maintainer, for honest reporting.
    pub fn maintainer_requirement_count(&self) -> usize {
        self.requirements
            .iter()
            .filter(|req| req.provenance == RequirementProvenance::MaintainerAuthored)
            .count()
    }
}

/// Collapse all whitespace runs to a single space and trim, so trivial
/// formatting edits do not invalidate the spec.
fn normalize_ws(value: &str) -> String {
    value.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn hash_len_prefixed(digest: &mut Sha256, value: &[u8]) {
    digest.update((value.len() as u64).to_be_bytes());
    digest.update(value);
}

#[cfg(test)]
mod tests {
    use super::*;

    fn inputs<'a>(comments: &'a [String]) -> TaskInputs<'a> {
        TaskInputs {
            issue_title: "Parser panics on empty input",
            issue_body: "Steps: run `p parse ''`. Expected: error, got panic.",
            maintainer_comments: comments,
            policy_excerpt: "Add a regression test for every bug fix.",
        }
    }

    fn spec() -> TaskSpec {
        let mut spec = TaskSpec::draft("owner/repo", Some(42), "Fix parser panic");
        spec.requirements.push(TaskRequirement {
            text: "Parser must return an error, not panic, on empty input".into(),
            provenance: RequirementProvenance::MaintainerAuthored,
        });
        spec.requirements.push(TaskRequirement {
            text: "Bug fixes need a regression test".into(),
            provenance: RequirementProvenance::RepositoryFact,
        });
        spec.requirements.push(TaskRequirement {
            text: "The panic likely originates in token stream initialization".into(),
            provenance: RequirementProvenance::ModelHypothesis,
        });
        spec.acceptance_criteria.push(AcceptanceCriterion {
            description: "cargo test parse_empty_returns_error passes".into(),
            provenance: RequirementProvenance::InferredCriterion,
            check_kind: "command".into(),
        });
        spec.ambiguities
            .push("Should empty input return EmptyInput or InvalidInput?".into());
        spec.finalize(&inputs(&[]))
    }

    #[test]
    fn fingerprint_is_deterministic_and_covers_all_fields() {
        let a = spec();
        let b = spec();
        assert_eq!(a.fingerprint, b.fingerprint);
        assert_eq!(a.fingerprint.len(), 64);

        let mut c = spec();
        c.ambiguities.clear();
        c.fingerprint = c.compute_fingerprint();
        assert_ne!(a.fingerprint, c.fingerprint);

        let mut d = spec();
        d.requirements[0].text.push_str(" please");
        d.fingerprint = d.compute_fingerprint();
        assert_ne!(a.fingerprint, d.fingerprint);
    }

    #[test]
    fn whitespace_only_changes_do_not_alter_fingerprint() {
        let mut a = TaskSpec::draft("o/r", None, "title");
        a.requirements.push(TaskRequirement {
            text: "do the   thing\nnow".into(),
            provenance: RequirementProvenance::RepositoryFact,
        });
        let a = a.finalize(&TaskInputs::default());

        let mut b = TaskSpec::draft("o/r", None, "title");
        b.requirements.push(TaskRequirement {
            text: "do the thing now".into(),
            provenance: RequirementProvenance::RepositoryFact,
        });
        let b = b.finalize(&TaskInputs::default());
        assert_eq!(a.fingerprint, b.fingerprint);
    }

    #[test]
    fn staleness_detects_changed_maintainer_input() {
        let comments = vec!["please also cover CRLF input".to_string()];
        let spec = spec();
        assert!(spec.inputs_are_current(&inputs(&[])));

        // Maintainer added a comment — the spec is now stale.
        assert!(!spec.inputs_are_current(&inputs(&comments)));

        // Changed issue body is also stale.
        let mut changed = inputs(&[]);
        changed.issue_body = "Different reproduction steps.";
        assert!(!spec.inputs_are_current(&changed));
    }

    #[test]
    fn provenance_counts_distinguish_authored_from_inferred() {
        let spec = spec();
        assert_eq!(spec.maintainer_requirement_count(), 1);
        assert!(spec
            .requirements
            .iter()
            .any(|r| r.provenance == RequirementProvenance::ModelHypothesis));
    }
}
